[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
reed-solomon-erasure = { version = "6.0", features = [ "simd-accel" ] }
rand = { version = "0.7.2", features = ["small_rng"] }
